algoritmo "conteAOinfinitoEalem"
var
contador:inteiro
valor:inteiro
salto:inteiro
inicio
      contador <- 0
      escreva("Quer contar ate quanto?")
      leia(valor)
       escreva("Qual sera o valor do salto?")
       leia(salto)
      enquanto (contador <= valor )faca
               escreval(contador)
               contador <- contador + salto
      fimenquanto
      escreval("O Aproveitamento do Aluno foi :",)
fimalgoritmo
